#pragma once

#include "common/timer.h"
#include "common/draw.h"
#include "common/types.h"
#include "HoughLines/HoughLines.h"
#include "Scale/Scale.h"
#include "Filter2D/Filter2D.h"
#include "Resize/Resize.h"
#include "SepFilter2D/SepFilter2D.h"
#include "ColorConvert/ColorConvert.h"
#include "ConvertBitDepth/ConvertBitDepth.h"
#include "Sobel/Sobel.h"
#include "WrapRotate/WrapRotate.h"
#include "Rotate/Rotate.h"
#include "Flip/Flip.h"
#include "Transpose/Transposeh.h"
#include "Translate/Translate.h"